version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app_new_bot
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    ports:
      - 6001:6001

  #Nginx Service
  webserver_new:
    image: nginx:alpine
    container_name: webserver_new_bot
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"

    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db_mysql:
    image: mysql:5.7.22
    container_name: db_mysql_bot
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bot
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_bot
    links:
      - db_mysql:db
    ports:
      - 8001:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: your_mysql_root_password
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    depends_on:
      - db_mysql
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local